// Mocks generated by Mockito 5.4.6 from annotations
// in oasis/test/collaborative_posts_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i13;

import 'package:flutter/foundation.dart' as _i16;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:oasis/features/auth/domain/models/app_user.dart' as _i2;
import 'package:oasis/features/circles/domain/models/circles_models.dart'
    as _i6;
import 'package:oasis/features/circles/presentation/providers/circle_provider.dart'
    as _i5;
import 'package:oasis/features/feed/domain/models/post.dart' as _i14;
import 'package:oasis/features/profile/domain/models/user_profile_entity.dart'
    as _i4;
import 'package:oasis/features/profile/presentation/providers/profile_provider.dart'
    as _i3;
import 'package:oasis/features/ripples/domain/models/ripple_entity.dart'
    as _i15;
import 'package:oasis/features/settings/domain/models/user_settings_entity.dart'
    as _i19;
import 'package:oasis/features/settings/presentation/providers/user_settings_provider.dart'
    as _i17;
import 'package:oasis/models/feed_layout_strategy.dart' as _i18;
import 'package:oasis/services/auth_service.dart' as _i8;
import 'package:oasis/services/session_registry_service.dart' as _i9;
import 'package:supabase_flutter/supabase_flutter.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppUser_0 extends _i1.SmartFake implements _i2.AppUser {
  _FakeAppUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileState_1 extends _i1.SmartFake implements _i3.ProfileState {
  _FakeProfileState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfileEntity_2 extends _i1.SmartFake
    implements _i4.UserProfileEntity {
  _FakeUserProfileEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCircleState_3 extends _i1.SmartFake implements _i5.CircleState {
  _FakeCircleState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCircleEntity_4 extends _i1.SmartFake implements _i6.CircleEntity {
  _FakeCircleEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_5 extends _i1.SmartFake
    implements _i7.FunctionsClient {
  _FakeFunctionsClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_6 extends _i1.SmartFake
    implements _i7.SupabaseStorageClient {
  _FakeSupabaseStorageClient_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_7 extends _i1.SmartFake
    implements _i7.RealtimeClient {
  _FakeRealtimeClient_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_8 extends _i1.SmartFake
    implements _i7.PostgrestClient {
  _FakePostgrestClient_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_9 extends _i1.SmartFake implements _i7.GoTrueClient {
  _FakeGoTrueClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_10 extends _i1.SmartFake
    implements _i7.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_11 extends _i1.SmartFake
    implements _i7.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_12<T1> extends _i1.SmartFake
    implements _i7.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_13 extends _i1.SmartFake
    implements _i7.RealtimeChannel {
  _FakeRealtimeChannel_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  @override
  List<_i9.RegisteredAccount> get registeredAccounts =>
      (super.noSuchMethod(
            Invocation.getter(#registeredAccounts),
            returnValue: <_i9.RegisteredAccount>[],
            returnValueForMissingStub: <_i9.RegisteredAccount>[],
          )
          as List<_i9.RegisteredAccount>);

  @override
  bool get isLoadingRegistry =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingRegistry),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Stream<_i7.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i10.Stream<_i7.AuthState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i7.AuthState>.empty(),
          )
          as _i10.Stream<_i7.AuthState>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setAddingAccount(bool? value) => super.noSuchMethod(
    Invocation.method(#setAddingAccount, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> switchAccount(_i11.BuildContext? context, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [context, userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void resetProviders(_i11.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#resetProviders, [context]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> removeAccount(_i11.BuildContext? context, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [context, userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.AppUser> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i10.Future<_i2.AppUser>);

  @override
  _i10.Future<_i2.AppUser> registerWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? username,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #username: username,
              #displayName: displayName,
            }),
            returnValue: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                  #displayName: displayName,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.AppUser>);

  @override
  _i10.Future<_i2.AppUser> signInWithGoogle({bool? forceSignIn = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [], {
              #forceSignIn: forceSignIn,
            }),
            returnValue: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(
                this,
                Invocation.method(#signInWithGoogle, [], {
                  #forceSignIn: forceSignIn,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(
                this,
                Invocation.method(#signInWithGoogle, [], {
                  #forceSignIn: forceSignIn,
                }),
              ),
            ),
          )
          as _i10.Future<_i2.AppUser>);

  @override
  _i10.Future<_i2.AppUser> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(this, Invocation.method(#signInWithApple, [])),
            ),
            returnValueForMissingStub: _i10.Future<_i2.AppUser>.value(
              _FakeAppUser_0(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i10.Future<_i2.AppUser>);

  @override
  _i10.Future<void> signOut({
    _i11.BuildContext? context,
    bool? forgetAccount = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {
              #context: context,
              #forgetAccount: forgetAccount,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> updateProfile({
    String? username,
    String? displayName,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #username: username,
              #displayName: displayName,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> uploadProfilePicture(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [filePath]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePicture, [filePath]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePicture, [filePath]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<String?> getPublicKey(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKey, [userId]),
            returnValue: _i10.Future<String?>.value(),
            returnValueForMissingStub: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<Map<String, String>> getPublicKeys(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKeys, [userIds]),
            returnValue: _i10.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i10.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i10.Future<Map<String, String>>);

  @override
  _i10.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileProvider extends _i1.Mock implements _i3.ProfileProvider {
  @override
  _i3.ProfileState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeProfileState_1(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeProfileState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.ProfileState);

  @override
  List<_i4.UserProfileEntity> get followers =>
      (super.noSuchMethod(
            Invocation.getter(#followers),
            returnValue: <_i4.UserProfileEntity>[],
            returnValueForMissingStub: <_i4.UserProfileEntity>[],
          )
          as List<_i4.UserProfileEntity>);

  @override
  List<_i4.UserProfileEntity> get following =>
      (super.noSuchMethod(
            Invocation.getter(#following),
            returnValue: <_i4.UserProfileEntity>[],
            returnValueForMissingStub: <_i4.UserProfileEntity>[],
          )
          as List<_i4.UserProfileEntity>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoadingFollowing =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingFollowing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isFollowing =>
      (super.noSuchMethod(
            Invocation.getter(#isFollowing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> loadCurrentProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadCurrentProfile, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadProfile(String? userId, String? currentUserId) =>
      (super.noSuchMethod(
            Invocation.method(#loadProfile, [userId, currentUserId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateProfile({
    required String? userId,
    String? username,
    String? fullName,
    String? bio,
    String? location,
    String? website,
    String? bannerColor,
    String? avatarFilePath,
    String? bannerFilePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #userId: userId,
              #username: username,
              #fullName: fullName,
              #bio: bio,
              #location: location,
              #website: website,
              #bannerColor: bannerColor,
              #avatarFilePath: avatarFilePath,
              #bannerFilePath: bannerFilePath,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> followUser({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [], {
              #followerId: followerId,
              #followingId: followingId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> acceptFollowRequest({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFollowRequest, [], {
              #followerId: followerId,
              #followingId: followingId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> declineFollowRequest({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#declineFollowRequest, [], {
              #followerId: followerId,
              #followingId: followingId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> checkFollowRequestStatus({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkFollowRequestStatus, [], {
              #followerId: followerId,
              #followingId: followingId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> unfollowUser({
    required String? followerId,
    required String? followingId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [], {
              #followerId: followerId,
              #followingId: followingId,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadFollowers(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadFollowers, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadFollowing(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadFollowing, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i4.UserProfileEntity>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i10.Future<List<_i4.UserProfileEntity>>.value(
              <_i4.UserProfileEntity>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i4.UserProfileEntity>>.value(
                  <_i4.UserProfileEntity>[],
                ),
          )
          as _i10.Future<List<_i4.UserProfileEntity>>);

  @override
  _i10.Future<List<_i14.Post>> loadSavedPosts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedPosts, [userId]),
            returnValue: _i10.Future<List<_i14.Post>>.value(<_i14.Post>[]),
            returnValueForMissingStub: _i10.Future<List<_i14.Post>>.value(
              <_i14.Post>[],
            ),
          )
          as _i10.Future<List<_i14.Post>>);

  @override
  _i10.Future<List<_i15.RippleEntity>> loadSavedRipples(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedRipples, [userId]),
            returnValue: _i10.Future<List<_i15.RippleEntity>>.value(
              <_i15.RippleEntity>[],
            ),
            returnValueForMissingStub:
                _i10.Future<List<_i15.RippleEntity>>.value(
                  <_i15.RippleEntity>[],
                ),
          )
          as _i10.Future<List<_i15.RippleEntity>>);

  @override
  _i10.Future<void> updatePrivacy({
    required String? userId,
    required bool? isPrivate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrivacy, [], {
              #userId: userId,
              #isPrivate: isPrivate,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void clearViewedProfile() => super.noSuchMethod(
    Invocation.method(#clearViewedProfile, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<_i4.UserProfileEntity> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i10.Future<_i4.UserProfileEntity>.value(
              _FakeUserProfileEntity_2(
                this,
                Invocation.method(#getProfile, [userId]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i4.UserProfileEntity>.value(
              _FakeUserProfileEntity_2(
                this,
                Invocation.method(#getProfile, [userId]),
              ),
            ),
          )
          as _i10.Future<_i4.UserProfileEntity>);

  @override
  _i10.Future<String> getOrCreateConversation({
    required String? user1Id,
    required String? user2Id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateConversation, [], {
              #user1Id: user1Id,
              #user2Id: user2Id,
            }),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateConversation, [], {
                  #user1Id: user1Id,
                  #user2Id: user2Id,
                }),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getOrCreateConversation, [], {
                  #user1Id: user1Id,
                  #user2Id: user2Id,
                }),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> runSafe(_i16.AsyncCallback? task) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [task]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [CircleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCircleProvider extends _i1.Mock implements _i5.CircleProvider {
  @override
  _i5.CircleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCircleState_3(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeCircleState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.CircleState);

  @override
  List<_i6.CircleEntity> get circles =>
      (super.noSuchMethod(
            Invocation.getter(#circles),
            returnValue: <_i6.CircleEntity>[],
            returnValueForMissingStub: <_i6.CircleEntity>[],
          )
          as List<_i6.CircleEntity>);

  @override
  List<_i14.Post> get circleFeed =>
      (super.noSuchMethod(
            Invocation.getter(#circleFeed),
            returnValue: <_i14.Post>[],
            returnValueForMissingStub: <_i14.Post>[],
          )
          as List<_i14.Post>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoadingFeed =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingFeed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasMoreFeed =>
      (super.noSuchMethod(
            Invocation.getter(#hasMoreFeed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> loadCircleFeed(
    String? circleId,
    String? userId, {
    bool? refresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadCircleFeed,
              [circleId, userId],
              {#refresh: refresh},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> createCirclePost({
    required String? circleId,
    required String? userId,
    String? content,
    List<String>? mediaUrls = const [],
    List<String>? mediaTypes = const [],
    String? mood,
    List<String>? hashtags = const [],
    bool? isSpoiler = false,
    Map<String, dynamic>? poll,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCirclePost, [], {
              #circleId: circleId,
              #userId: userId,
              #content: content,
              #mediaUrls: mediaUrls,
              #mediaTypes: mediaTypes,
              #mood: mood,
              #hashtags: hashtags,
              #isSpoiler: isSpoiler,
              #poll: poll,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> toggleLike(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [postId, userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> addCommitment({
    required String? createdBy,
    required String? title,
    String? description,
    DateTime? dueDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCommitment, [], {
              #createdBy: createdBy,
              #title: title,
              #description: description,
              #dueDate: dueDate,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadCircles(String? userId, {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadCircles,
              [userId],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i6.CircleEntity?> createCircle({
    required String? createdBy,
    required String? name,
    required String? emoji,
    required List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCircle, [], {
              #createdBy: createdBy,
              #name: name,
              #emoji: emoji,
              #memberIds: memberIds,
            }),
            returnValue: _i10.Future<_i6.CircleEntity?>.value(),
            returnValueForMissingStub: _i10.Future<_i6.CircleEntity?>.value(),
          )
          as _i10.Future<_i6.CircleEntity?>);

  @override
  _i10.Future<_i6.CircleEntity> getCircle(String? circleId) =>
      (super.noSuchMethod(
            Invocation.method(#getCircle, [circleId]),
            returnValue: _i10.Future<_i6.CircleEntity>.value(
              _FakeCircleEntity_4(
                this,
                Invocation.method(#getCircle, [circleId]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<_i6.CircleEntity>.value(
              _FakeCircleEntity_4(
                this,
                Invocation.method(#getCircle, [circleId]),
              ),
            ),
          )
          as _i10.Future<_i6.CircleEntity>);

  @override
  _i10.Future<void> joinCircle(String? circleId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#joinCircle, [circleId, userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setActiveCircle(String? circleId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveCircle, [circleId, userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void closeCircle() => super.noSuchMethod(
    Invocation.method(#closeCircle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> deleteCircle(String? circleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCircle, [circleId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deletePost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId, userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> runSafe(_i16.AsyncCallback? task) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [task]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [UserSettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsProvider extends _i1.Mock
    implements _i17.UserSettingsProvider {
  @override
  bool get dataSaver =>
      (super.noSuchMethod(
            Invocation.getter(#dataSaver),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get fontSizeFactor =>
      (super.noSuchMethod(
            Invocation.getter(#fontSizeFactor),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get highContrast =>
      (super.noSuchMethod(
            Invocation.getter(#highContrast),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get dailyLimitMinutes =>
      (super.noSuchMethod(
            Invocation.getter(#dailyLimitMinutes),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get windDownEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#windDownEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get micaEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#micaEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get windowEffect =>
      (super.noSuchMethod(
            Invocation.getter(#windowEffect),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#windowEffect),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#windowEffect),
            ),
          )
          as String);

  @override
  String get fontFamily =>
      (super.noSuchMethod(
            Invocation.getter(#fontFamily),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#fontFamily),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.getter(#fontFamily),
            ),
          )
          as String);

  @override
  _i18.FeedLayoutType get feedLayout =>
      (super.noSuchMethod(
            Invocation.getter(#feedLayout),
            returnValue: _i18.FeedLayoutType.classic,
            returnValueForMissingStub: _i18.FeedLayoutType.classic,
          )
          as _i18.FeedLayoutType);

  @override
  _i19.LiquidGlassMode get liquidGlassMode =>
      (super.noSuchMethod(
            Invocation.getter(#liquidGlassMode),
            returnValue: _i19.LiquidGlassMode.disabled,
            returnValueForMissingStub: _i19.LiquidGlassMode.disabled,
          )
          as _i19.LiquidGlassMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setMicaEnabled(bool? value, {bool? isDark = true}) =>
      (super.noSuchMethod(
            Invocation.method(#setMicaEnabled, [value], {#isDark: isDark}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setWindowEffect(String? value, {bool? isDark = true}) =>
      (super.noSuchMethod(
            Invocation.method(#setWindowEffect, [value], {#isDark: isDark}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setDailyLimit(int? minutes) =>
      (super.noSuchMethod(
            Invocation.method(#setDailyLimit, [minutes]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setWindDownEnabled(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setWindDownEnabled, [value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setDataSaver(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDataSaver, [value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setFontSizeFactor(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFontSizeFactor, [value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setHighContrast(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHighContrast, [value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setFontFamily(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFontFamily, [value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setFeedLayout(_i18.FeedLayoutType? layout) =>
      (super.noSuchMethod(
            Invocation.method(#setFeedLayout, [layout]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setLiquidGlassMode(_i19.LiquidGlassMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setLiquidGlassMode, [mode]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> runSafe(_i16.AsyncCallback? task) =>
      (super.noSuchMethod(
            Invocation.method(#runSafe, [task]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i7.SupabaseClient {
  @override
  _i7.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_5(
              this,
              Invocation.getter(#functions),
            ),
            returnValueForMissingStub: _FakeFunctionsClient_5(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i7.FunctionsClient);

  @override
  _i7.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_6(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeSupabaseStorageClient_6(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i7.SupabaseStorageClient);

  @override
  _i7.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_7(
              this,
              Invocation.getter(#realtime),
            ),
            returnValueForMissingStub: _FakeRealtimeClient_7(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i7.RealtimeClient);

  @override
  _i7.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_8(this, Invocation.getter(#rest)),
            returnValueForMissingStub: _FakePostgrestClient_8(
              this,
              Invocation.getter(#rest),
            ),
          )
          as _i7.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
            returnValueForMissingStub: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i7.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_9(this, Invocation.getter(#auth)),
            returnValueForMissingStub: _FakeGoTrueClient_9(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i7.GoTrueClient);

  @override
  set functions(_i7.FunctionsClient? value) => super.noSuchMethod(
    Invocation.setter(#functions, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i7.SupabaseStorageClient? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i7.RealtimeClient? value) => super.noSuchMethod(
    Invocation.setter(#realtime, value),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i7.PostgrestClient? value) => super.noSuchMethod(
    Invocation.setter(#rest, value),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i7.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_10(
              this,
              Invocation.method(#from, [table]),
            ),
            returnValueForMissingStub: _FakeSupabaseQueryBuilder_10(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i7.SupabaseQueryBuilder);

  @override
  _i7.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_11(
              this,
              Invocation.method(#schema, [schema]),
            ),
            returnValueForMissingStub: _FakeSupabaseQuerySchema_11(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i7.SupabaseQuerySchema);

  @override
  _i7.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_12<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
            returnValueForMissingStub: _FakePostgrestFilterBuilder_12<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i7.PostgrestFilterBuilder<T>);

  @override
  _i7.RealtimeChannel channel(
    String? name, {
    _i7.RealtimeChannelConfig? opts = const _i7.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_13(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
            returnValueForMissingStub: _FakeRealtimeChannel_13(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i7.RealtimeChannel);

  @override
  List<_i7.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i7.RealtimeChannel>[],
            returnValueForMissingStub: <_i7.RealtimeChannel>[],
          )
          as List<_i7.RealtimeChannel>);

  @override
  _i10.Future<String> removeChannel(_i7.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
            returnValueForMissingStub: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i10.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
