// Mocks generated by Mockito 5.4.6 from annotations
// in oasis/test/notification_decryption_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i8;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i16;

import 'package:encrypt/encrypt.dart' as _i7;
import 'package:flutter/material.dart' as _i15;
import 'package:libsignal_protocol_dart/libsignal_protocol_dart.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:oasis/features/auth/domain/models/app_user.dart' as _i4;
import 'package:oasis/features/messages/data/encryption_service.dart' as _i2;
import 'package:oasis/features/messages/data/signal/signal_service.dart'
    as _i10;
import 'package:oasis/services/auth_service.dart' as _i12;
import 'package:oasis/services/key_management_service.dart' as _i6;
import 'package:oasis/services/session_registry_service.dart' as _i13;
import 'package:supabase_flutter/supabase_flutter.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEncryptedMessage_0 extends _i1.SmartFake
    implements _i2.EncryptedMessage {
  _FakeEncryptedMessage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCiphertextMessage_1 extends _i1.SmartFake
    implements _i3.CiphertextMessage {
  _FakeCiphertextMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUser_2 extends _i1.SmartFake implements _i4.AppUser {
  _FakeAppUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i2.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Future<_i6.EncryptionStatus> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<_i6.EncryptionStatus>.value(
              _i6.EncryptionStatus.ready,
            ),
          )
          as _i5.Future<_i6.EncryptionStatus>);

  @override
  _i5.Future<bool> restoreSecureKeys(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#restoreSecureKeys, [pin]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> restoreWithRecoveryKey(String? recoveryKey) =>
      (super.noSuchMethod(
            Invocation.method(#restoreWithRecoveryKey, [recoveryKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<({String? recoveryKey, bool success})> upgradeSecurity(
    String? pin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeSecurity, [pin]),
            returnValue:
                _i5.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i5.Future<({String? recoveryKey, bool success})>);

  @override
  _i5.Future<({String? recoveryKey, bool success})> setupEncryption({
    String? pin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setupEncryption, [], {#pin: pin}),
            returnValue:
                _i5.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i5.Future<({String? recoveryKey, bool success})>);

  @override
  _i5.Future<_i2.EncryptedMessage> encryptMessage(
    String? content,
    List<String>? recipientPublicKeysPem, {
    _i7.Key? reuseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [content, recipientPublicKeysPem],
              {#reuseKey: reuseKey},
            ),
            returnValue: _i5.Future<_i2.EncryptedMessage>.value(
              _FakeEncryptedMessage_0(
                this,
                Invocation.method(
                  #encryptMessage,
                  [content, recipientPublicKeysPem],
                  {#reuseKey: reuseKey},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.EncryptedMessage>);

  @override
  _i5.Future<String?> decryptMessage(
    String? encryptedContentBase64,
    Map<String, dynamic>? encryptedKeys,
    String? ivBase64, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decryptMessage,
              [encryptedContentBase64, encryptedKeys, ivBase64],
              {#userId: userId},
            ),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<Map<String, dynamic>> encryptMediaFile({
    required _i8.File? file,
    required List<String>? recipientPublicKeysPem,
    List<String>? recipientUserIds,
    String? recipientUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encryptMediaFile, [], {
              #file: file,
              #recipientPublicKeysPem: recipientPublicKeysPem,
              #recipientUserIds: recipientUserIds,
              #recipientUserId: recipientUserId,
            }),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i9.Uint8List?> decryptMediaFile({
    required _i9.Uint8List? encryptedBytes,
    required String? ivBase64,
    required Map<String, dynamic>? encryptedKeys,
    String? senderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMediaFile, [], {
              #encryptedBytes: encryptedBytes,
              #ivBase64: ivBase64,
              #encryptedKeys: encryptedKeys,
              #senderId: senderId,
            }),
            returnValue: _i5.Future<_i9.Uint8List?>.value(),
          )
          as _i5.Future<_i9.Uint8List?>);

  @override
  _i5.Future<bool> generateNewKeys() =>
      (super.noSuchMethod(
            Invocation.method(#generateNewKeys, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<({String? recoveryKey, bool success})> generateNewKeysWithPin(
    String? pin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateNewKeysWithPin, [pin]),
            returnValue:
                _i5.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i5.Future<({String? recoveryKey, bool success})>);

  @override
  _i5.Future<bool> restoreKeys() =>
      (super.noSuchMethod(
            Invocation.method(#restoreKeys, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> backupSignalIdentity(
    String? identityKeyPairBase64,
    int? registrationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#backupSignalIdentity, [
              identityKeyPairBase64,
              registrationId,
            ]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> restoreSignalIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSignalIdentity, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> clearKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearKeys, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SignalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignalService extends _i1.Mock implements _i10.SignalService {
  MockSignalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> init({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#init, [], {#userId: userId}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearData({String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#clearData, [], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forceRefreshBundle(
    String? remoteUserId, {
    String? localUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #forceRefreshBundle,
              [remoteUserId],
              {#localUserId: localUserId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.CiphertextMessage> encryptMessage(
    String? recipientId,
    String? plaintext, {
    String? localUserId,
    int? deviceId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [recipientId, plaintext],
              {#localUserId: localUserId, #deviceId: deviceId},
            ),
            returnValue: _i5.Future<_i3.CiphertextMessage>.value(
              _FakeCiphertextMessage_1(
                this,
                Invocation.method(
                  #encryptMessage,
                  [recipientId, plaintext],
                  {#localUserId: localUserId, #deviceId: deviceId},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.CiphertextMessage>);

  @override
  _i5.Future<String> decryptMessage(
    String? senderId,
    String? base64Ciphertext,
    int? type, {
    String? localUserId,
    int? deviceId = 1,
    bool? isHistorical = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decryptMessage,
              [senderId, base64Ciphertext, type],
              {
                #localUserId: localUserId,
                #deviceId: deviceId,
                #isHistorical: isHistorical,
              },
            ),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(
                  #decryptMessage,
                  [senderId, base64Ciphertext, type],
                  {
                    #localUserId: localUserId,
                    #deviceId: deviceId,
                    #isHistorical: isHistorical,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<String>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i12.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.RegisteredAccount> get registeredAccounts =>
      (super.noSuchMethod(
            Invocation.getter(#registeredAccounts),
            returnValue: <_i13.RegisteredAccount>[],
          )
          as List<_i13.RegisteredAccount>);

  @override
  _i5.Stream<_i14.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i14.AuthState>.empty(),
          )
          as _i5.Stream<_i14.AuthState>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setAddingAccount(bool? value) => super.noSuchMethod(
    Invocation.method(#setAddingAccount, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> switchAccount(_i15.BuildContext? context, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [context, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void resetProviders(_i15.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#resetProviders, [context]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> removeAccount(_i15.BuildContext? context, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [context, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.AppUser> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i5.Future<_i4.AppUser>.value(
              _FakeAppUser_2(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i5.Future<_i4.AppUser>);

  @override
  _i5.Future<_i4.AppUser> registerWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? username,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #username: username,
              #displayName: displayName,
            }),
            returnValue: _i5.Future<_i4.AppUser>.value(
              _FakeAppUser_2(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.AppUser>);

  @override
  _i5.Future<_i4.AppUser> signInWithGoogle({bool? forceSignIn = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [], {
              #forceSignIn: forceSignIn,
            }),
            returnValue: _i5.Future<_i4.AppUser>.value(
              _FakeAppUser_2(
                this,
                Invocation.method(#signInWithGoogle, [], {
                  #forceSignIn: forceSignIn,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.AppUser>);

  @override
  _i5.Future<_i4.AppUser> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<_i4.AppUser>.value(
              _FakeAppUser_2(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i5.Future<_i4.AppUser>);

  @override
  _i5.Future<void> signOut({_i15.BuildContext? context}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#context: context}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> updateProfile({
    String? username,
    String? displayName,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #username: username,
              #displayName: displayName,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> uploadProfilePicture(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [filePath]),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePicture, [filePath]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String?> getPublicKey(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKey, [userId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<Map<String, String>> getPublicKeys(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKeys, [userIds]),
            returnValue: _i5.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
