// Mocks generated by Mockito 5.4.6 from annotations
// in oasis/test/notification_decryption_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i8;
import 'dart:typed_data' as _i7;
import 'dart:ui' as _i15;

import 'package:encrypt/encrypt.dart' as _i2;
import 'package:flutter/material.dart' as _i14;
import 'package:libsignal_protocol_dart/libsignal_protocol_dart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:oasis/features/auth/domain/models/app_user.dart' as _i5;
import 'package:oasis/features/messages/data/encryption_service.dart' as _i3;
import 'package:oasis/features/messages/data/signal/signal_service.dart' as _i9;
import 'package:oasis/services/auth_service.dart' as _i11;
import 'package:oasis/services/session_registry_service.dart' as _i12;
import 'package:supabase_flutter/supabase_flutter.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKey_0 extends _i1.SmartFake implements _i2.Key {
  _FakeKey_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryptedMessage_1 extends _i1.SmartFake
    implements _i3.EncryptedMessage {
  _FakeEncryptedMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCiphertextMessage_2 extends _i1.SmartFake
    implements _i4.CiphertextMessage {
  _FakeCiphertextMessage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppUser_3 extends _i1.SmartFake implements _i5.AppUser {
  _FakeAppUser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i3.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Future<dynamic> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<bool> restoreSecureKeys(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#restoreSecureKeys, [pin]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> restoreWithRecoveryKey(String? recoveryKey) =>
      (super.noSuchMethod(
            Invocation.method(#restoreWithRecoveryKey, [recoveryKey]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<({String? recoveryKey, bool success})> resetPinWithRecoveryKey(
    String? recoveryKey,
    String? newPin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPinWithRecoveryKey, [recoveryKey, newPin]),
            returnValue:
                _i6.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i6.Future<({String? recoveryKey, bool success})>);

  @override
  _i6.Future<({String? recoveryKey, bool success})> upgradeSecurity(
    String? pin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upgradeSecurity, [pin]),
            returnValue:
                _i6.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i6.Future<({String? recoveryKey, bool success})>);

  @override
  _i6.Future<bool> generateNewKeys() =>
      (super.noSuchMethod(
            Invocation.method(#generateNewKeys, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<({String? recoveryKey, bool success})> generateNewKeysWithPin(
    String? pin,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateNewKeysWithPin, [pin]),
            returnValue:
                _i6.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i6.Future<({String? recoveryKey, bool success})>);

  @override
  _i6.Future<({String? recoveryKey, bool success})> setupEncryption({
    String? pin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setupEncryption, [], {#pin: pin}),
            returnValue:
                _i6.Future<({String? recoveryKey, bool success})>.value((
                  recoveryKey: null,
                  success: false,
                )),
          )
          as _i6.Future<({String? recoveryKey, bool success})>);

  @override
  _i6.Future<bool> restoreKeys() =>
      (super.noSuchMethod(
            Invocation.method(#restoreKeys, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i2.Key generateAESKey() =>
      (super.noSuchMethod(
            Invocation.method(#generateAESKey, []),
            returnValue: _FakeKey_0(
              this,
              Invocation.method(#generateAESKey, []),
            ),
          )
          as _i2.Key);

  @override
  _i7.Uint8List encryptData(_i7.Uint8List? data, _i2.Key? key) =>
      (super.noSuchMethod(
            Invocation.method(#encryptData, [data, key]),
            returnValue: _i7.Uint8List(0),
          )
          as _i7.Uint8List);

  @override
  _i7.Uint8List? decryptData(_i7.Uint8List? combinedData, _i2.Key? key) =>
      (super.noSuchMethod(Invocation.method(#decryptData, [combinedData, key]))
          as _i7.Uint8List?);

  @override
  _i6.Future<_i3.EncryptedMessage> encryptMessage(
    String? content,
    List<String>? recipientPublicKeysPem, {
    _i2.Key? reuseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [content, recipientPublicKeysPem],
              {#reuseKey: reuseKey},
            ),
            returnValue: _i6.Future<_i3.EncryptedMessage>.value(
              _FakeEncryptedMessage_1(
                this,
                Invocation.method(
                  #encryptMessage,
                  [content, recipientPublicKeysPem],
                  {#reuseKey: reuseKey},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.EncryptedMessage>);

  @override
  _i6.Future<String?> decryptMessage(
    String? encryptedContentBase64,
    Map<String, dynamic>? encryptedKeys,
    String? ivBase64,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMessage, [
              encryptedContentBase64,
              encryptedKeys,
              ivBase64,
            ]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, dynamic>> encryptMediaFile({
    required _i8.File? file,
    required List<String>? recipientPublicKeysPem,
    String? recipientUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encryptMediaFile, [], {
              #file: file,
              #recipientPublicKeysPem: recipientPublicKeysPem,
              #recipientUserId: recipientUserId,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i7.Uint8List?> decryptMediaFile({
    required _i7.Uint8List? encryptedBytes,
    required String? ivBase64,
    required Map<String, dynamic>? encryptedKeys,
    String? senderId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decryptMediaFile, [], {
              #encryptedBytes: encryptedBytes,
              #ivBase64: ivBase64,
              #encryptedKeys: encryptedKeys,
              #senderId: senderId,
            }),
            returnValue: _i6.Future<_i7.Uint8List?>.value(),
          )
          as _i6.Future<_i7.Uint8List?>);

  @override
  _i6.Future<bool> backupSignalIdentity(
    String? identityKeyPairBase64,
    int? registrationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#backupSignalIdentity, [
              identityKeyPairBase64,
              registrationId,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>?> restoreSignalIdentity() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSignalIdentity, []),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> clearKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearKeys, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SignalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignalService extends _i1.Mock implements _i9.SignalService {
  MockSignalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> clearData() =>
      (super.noSuchMethod(
            Invocation.method(#clearData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> forceRefreshBundle(String? remoteUserId) =>
      (super.noSuchMethod(
            Invocation.method(#forceRefreshBundle, [remoteUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.CiphertextMessage> encryptMessage(
    String? recipientId,
    String? plaintext, {
    int? deviceId = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encryptMessage,
              [recipientId, plaintext],
              {#deviceId: deviceId},
            ),
            returnValue: _i6.Future<_i4.CiphertextMessage>.value(
              _FakeCiphertextMessage_2(
                this,
                Invocation.method(
                  #encryptMessage,
                  [recipientId, plaintext],
                  {#deviceId: deviceId},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.CiphertextMessage>);

  @override
  _i6.Future<String> decryptMessage(
    String? senderId,
    String? base64Ciphertext,
    int? type, {
    int? deviceId = 1,
    bool? isHistorical = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #decryptMessage,
              [senderId, base64Ciphertext, type],
              {#deviceId: deviceId, #isHistorical: isHistorical},
            ),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #decryptMessage,
                  [senderId, base64Ciphertext, type],
                  {#deviceId: deviceId, #isHistorical: isHistorical},
                ),
              ),
            ),
          )
          as _i6.Future<String>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i11.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.RegisteredAccount> get registeredAccounts =>
      (super.noSuchMethod(
            Invocation.getter(#registeredAccounts),
            returnValue: <_i12.RegisteredAccount>[],
          )
          as List<_i12.RegisteredAccount>);

  @override
  _i6.Stream<_i13.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i6.Stream<_i13.AuthState>.empty(),
          )
          as _i6.Stream<_i13.AuthState>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> switchAccount(_i14.BuildContext? context, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [context, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeAccount(_i14.BuildContext? context, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [context, userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i5.AppUser> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i6.Future<_i5.AppUser>.value(
              _FakeAppUser_3(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i6.Future<_i5.AppUser>);

  @override
  _i6.Future<_i5.AppUser> registerWithEmailAndPassword({
    required String? email,
    required String? password,
    required String? username,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmailAndPassword, [], {
              #email: email,
              #password: password,
              #username: username,
              #displayName: displayName,
            }),
            returnValue: _i6.Future<_i5.AppUser>.value(
              _FakeAppUser_3(
                this,
                Invocation.method(#registerWithEmailAndPassword, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AppUser>);

  @override
  _i6.Future<_i5.AppUser> signInWithGoogle({bool? forceSignIn = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, [], {
              #forceSignIn: forceSignIn,
            }),
            returnValue: _i6.Future<_i5.AppUser>.value(
              _FakeAppUser_3(
                this,
                Invocation.method(#signInWithGoogle, [], {
                  #forceSignIn: forceSignIn,
                }),
              ),
            ),
          )
          as _i6.Future<_i5.AppUser>);

  @override
  _i6.Future<_i5.AppUser> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i6.Future<_i5.AppUser>.value(
              _FakeAppUser_3(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i6.Future<_i5.AppUser>);

  @override
  _i6.Future<void> signOut({_i14.BuildContext? context}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#context: context}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> updateProfile({
    String? username,
    String? displayName,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #username: username,
              #displayName: displayName,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> uploadProfilePicture(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [filePath]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePicture, [filePath]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String?> getPublicKey(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKey, [userId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, String>> getPublicKeys(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicKeys, [userIds]),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
