class R2Config {
  static const String r2BucketName = 'oasis';
  static const String b2FeedBucketName = 'oasis-feed';
  static const String b2RipplesBucketName = 'oasis-ripples';

  // These represent the public-facing or application-level URLs for when
  // the client needs to reconstruct paths. The actual sensitive upload/download
  // operations will be handled via Pre-Signed URLs generated by Supabase Edge Functions.

  // Note: The edge function 'generate-presigned-url' handles the actual S3 endpoints
  // and credentials securely on the backend.
  static const String presignedUrlFunctionName = 'generate-presigned-url';

  // Public access URL for files in R2 (unencrypted only)
  static const String r2PublicBaseUrl = 'https://pub-367b2ec139244405b5e1c1ab74e78467.r2.dev';
}
